# Generated by Django 4.2.7 on 2023-11-27 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='obligations',
            name='due_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='english_level',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='obligation_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='obligation_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='obligations',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
