# Generated by Django 4.2.7 on 2023-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0002_remove_student_email_obligations_due_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.AddField(
            model_name='teacher',
            name='working_days',
            field=models.CharField(default='', max_length=50),
        ),
    ]
