# Generated by Django 4.2.7 on 2023-11-27 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0003_remove_teacher_email_teacher_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='obligation_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
