# Generated by Django 4.2.7 on 2023-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_alter_student_obligation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='obligation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
