# Generated by Django 5.0 on 2023-12-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0005_alter_student_obligation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_pay',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
