# Generated by Django 5.0 on 2023-12-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0008_schedule_student_schedule_teacher_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='classapp.course'),
        ),
    ]
