# Generated by Django 5.0 on 2023-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0010_teacher_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
